name: final_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: any
  http: any
  json_serializable: any
  cupertino_icons: ^1.0.0
  smooth_page_indicator: any
  provider: any
  toast: any
  image_picker: any
  flutter_custom_clippers: any
  custom_bottom_navigation_bar: any
  curved_navigation_bar: any
  location: ^3.0.0
  bottom_navy_bar: ^5.6.0
  flutter_polyline_points: any
  geolocator: ^5.3.2+2
  modal_bottom_sheet: ^2.0.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.0
  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/photos/
    - assets/images/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalooTamma2
      fonts:
        - asset: assets/fonts/BalooTamma2-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
